### ISSUE TITLE
Remove FS dependency?

### ISSUE THREAD

**Issue by paf31** [purescript-node/purescript-node-process#2]
It only exists to pull in the `FS` effect, for `requireResolve`. Maybe we could just introduce a separate effect for this?

**Comment by hdgarrood** [comment]
I think introducing too many distinct effect types would be annoying for application developers, and `FS` does seem like the right effect for this. If dependencies are becoming a pain perhaps we should reconsider merging all the node APIs into a single package?

**Comment by garyb** [comment]
Or a variation on that: we could have all the node effects in a single package, perhaps?

**Comment by hdgarrood** [comment]
Yeah, that seems like it could work well.

**Comment by hdgarrood** [comment]
What are the others? `CHILD_PROCESS`, `PROCESS`, `HTTP`, `READLINE`, have I missed any?

**Comment by paf31** [comment]
Maybe some can be consolidated, like `READLINE` and `CONSOLE` or `CHILD_PROCESS` and `PROCESS`. I think a `SOCKET` or `NETWORK` effect would make sense to unify `node-sockets` and `HTTP` too.

**Comment by garyb** [comment]
`CHILD_PROCESS` and `PROCESS` can't really, the former is when you're spawning and manging other processes, whereas process is for finding out info about the current process. The distinction definitely seems worthwhile to me.

**Comment by hdgarrood** [comment]
Yeah, arguably we shouldn't merge READLINE and CONSOLE either, as readline has little to do with consoles specifically, it's for consuming plain text streams one line at a time. A NETWORK effect sounds like a good idea to me though.

**Comment by paf31** [comment]
I assumed readline was for reading `stdin` and console for writing to `stdout`.

**Comment by garyb** [comment]
One for this list: the `BUFFER` effect.
