### ISSUE TITLE
Should argv clone the array?

### ISSUE THREAD

**Issue by rightfold** [purescript-node/purescript-node-process#8]
> Get an array containing the command line arguments. Be aware that this can change over the course of the program.

Does this mean the array itself may change? Because if that happens, then `argv` should return a clone of the array to keep users of the array referentially transparent.

**Comment by hdgarrood** [comment]
Yes, the array itself can change, if you do something like `process.argv.push('wat')` in JS. I agree, cloning the array seems like the right thing to do. We might also consider exposing an API from this library that lets you mutate `process.argv` too.

**Comment by thomashoneyman** [comment]
I think we should try and fix this for the upcoming 0.14 release for this library.

**Comment by jvliwanag** [comment]
Perhaps we can simply set the type of argv as `STArray Global String` this adds a dependency on st though.

**Comment by jvliwanag** [comment]
Also, should we do the same for `execArgv` and `env`?

**Comment by hdgarrood** [comment]
I think I’d prefer just providing a pair of Effect functions to get and set these values, eg `argv :: Effect (Array String)` and `setArgv :: Array String -> Effect Unit`

**Comment by jvliwanag** [comment]
The neat think on the ST Global stuff is we can skip having to write custom ffi for freezing arrays and objects (for `env`). We can even delete the current ffi for `setEnv` and `unsetEnv`.

We can always just hide the functions exposing `ST Global` if that's an issue. Or are we better off keeping it simple and dropping the `ST Global` entirely?

**Comment by hdgarrood** [comment]
While it makes perfect sense to avoid FFI where possible in most contexts, I don’t think libraries whose purpose is to provide bindings to JS APIs is one of them. I think having custom FFI for these is fine.
